---
label: Theme configuration
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- type: textarea
  name: site_description
  label: Site description
- type: textarea
  name: hero_title
  label: Hero title
  config:
    wysiwyg: true
    schema:
      format: html
- type: textarea
  name: english_subtitle
  label: English Subtitle
  config:
    wysiwyg: true
    schema:
      format: html
- type: textarea
  name: subtítulo_en_español
  label: Subtítulo en Español
  config:
    wysiwyg: true
    schema:
      format: html
- type: boolean
  name: dark_mode
  label: Dark mode
pages:
- data/theme.json
